service: demo-ci-cd

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}

functions:
  sendEmail:
    name: ses-testing
    handler: index.handler
    events:
      - http:
          path: send-email
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
